@DotNet8.EmailVerification.Modules.Account.Presentation_HostAddress = http://localhost:5086

GET {{DotNet8.EmailVerification.Modules.Account.Presentation_HostAddress}}/weatherforecast/
Accept: application/json

###
